# Generated by Django 5.2 on 2025-05-09 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinearGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numbers_sponsor', models.PositiveIntegerField(default=0)),
                ('numbers_student', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Kunlik statistika',
                'verbose_name_plural': '5.Kunlik statistikalar',
            },
        ),
        migrations.CreateModel(
            name='MainDatas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_asked', models.PositiveIntegerField(default=0)),
                ('money_sent', models.PositiveIntegerField(default=0)),
                ('money_amount', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': "6.Asosiy ma'lumotlar",
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_phisical_person', models.BooleanField(choices=[(0, 'Yuridik'), (1, 'Jismoniy')], verbose_name='Shaxs turi')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.Sh')),
                ('phone', models.CharField(max_length=13, verbose_name='Telefon raqam')),
                ('name_company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Firma nomi')),
                ('condition', models.IntegerField(choices=[(1, 'Yangi'), (2, 'Tasdiqlangan'), (3, 'Moderatsiyada'), (4, 'Bekor qilingan')], default=1, verbose_name='Holat')),
                ('budget', models.PositiveIntegerField()),
                ('used', models.PositiveIntegerField(default=0)),
                ('is_counted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Homiy',
                'verbose_name_plural': '2.Homiylar',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.Sh')),
                ('phone', models.CharField(max_length=13, verbose_name='Telefon raqam')),
                ('student_type', models.IntegerField(choices=[(1, 'Bakalavr'), (2, 'Magistratura'), (3, 'Aspirantura')], verbose_name='Talim turi')),
                ('request', models.PositiveIntegerField(verbose_name='Soralgan pul miqdor')),
                ('send', models.PositiveIntegerField(default=0, verbose_name='Tolangan pul miqdori')),
            ],
            options={
                'verbose_name': 'Talaba',
                'verbose_name_plural': '3.Talabalar',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Universitet nomi')),
            ],
            options={
                'verbose_name': 'Universitet',
                'verbose_name_plural': '1.Universitetlar',
            },
        ),
        migrations.CreateModel(
            name='StudentBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('money', models.PositiveIntegerField(verbose_name='Pull miqdori')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.sponsor', verbose_name='Homiy')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.student', verbose_name='Talaba')),
            ],
            options={
                'verbose_name': 'Talaba va Homiy',
                'verbose_name_plural': '4.Talabalar va Homiylar',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.university', verbose_name='Institut'),
        ),
    ]
