# Generated by Django 5.2 on 2025-05-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineargraph',
            name='day',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
